// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using karaaslanlar1.Models;

#nullable disable

namespace karaaslanlar1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516141811_AfetTuruEkleme")]
    partial class AfetTuruEkleme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("karaaslanlar1.Models.AfetTalebi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Derecesi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lokasyon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Turu")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Talepler");
                });
#pragma warning restore 612, 618
        }
    }
}
